### PR TITLE
feat: add interactive demos

### PR DESCRIPTION
**Pull request by erayalkis**
demo

This PR creates 3 new interactive demos, as written in issue #15. I have tested the behaviour of the frontend, and everything seems to work as expected.
No tests have been written for this new feature so far, and I will get to work on them ASAP if necessary. :)

### Description of change

- Creates a new interactive HTML demo.
  - Creates demos/html/index.html, demos/html/index.css and demos/html/index.js. 
    - The JS file uses a jsdelivr CDN to fetch a browser-friendly version of @zootools/email-spell-checker.
    - The HTML file uses a fontawesome CDN for icons.
- Creates a new interactive React demo.
- Creates a new interactive Vue.js demo.
- Adds documentation for all new demos.

### Pull-Request Checklist

- [x] Code is up-to-date with the `main` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by ferreiro** [comment]
@erayalkis wow! this is awesome, thanks for doing this. will review it in the upcoming days. mind to record a gif or screenshots and attach them to this PR so we can document it?

for another PRs, it'd be cool to replicate your example into other popular FE libraries like React or Vue. what do you think?

**Comment by erayalkis** [comment]
Thanks Jorge! Absolutely, I'll set up a short gif for the PR description real quick.😄I'll also get started on setting up the example on React and Vue, it'll be more helpful this way for sure!

**Comment by ferreiro** [comment]
cool @erayalkis -- ty!

**Comment by ferreiro** [comment]
@erayalkis hey! I tried your html version and I got a CORS issue. Know what's happening and how to fix it? Also, any other way to import the JS from the CDN that will be browser-compatible? I saw you are using the import and wondering if that will break in some browsers.

https://www.loom.com/share/67dd16d0a9974032a1a25b28a2ba6abe?from_recorder=1&focus_title=1

**Comment by erayalkis** [comment]
Hi @ferreiro ! Yep, I think I know what's going on. IIRC, a CORS error like this is caused by trying to import local files, it should be quite easy to fix :) I'll open an issue and create a PR to fix it as soon as possible!

**Pull request merged**
